let a=10;
let b=20;
console.log(a==b);
console.log(a!=b);
console.log(a>b);
console.log(a<b);
console.log(a>=b);
console.log(a<=b);
let a1 = 10;
let b1 = "10";
console.log(a1==b1);
console.log(a1===b1);
console.log(a1!=b1);
console.log(a1!==b1);
let a2 = 20;
let b2 = 20;
console.log(a2==b2);
console.log(a2===b2);
console.log(a2!=b2);
console.log(a2!==b2);